name: Update Localization Tracker

on:
  push:
    branches:
      - 'main'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Find Comment
      id: fc
      uses: peter-evans/find-comment@v2
      with:
        issue-number: ${{ vars.LOCALIZATION_TRACKER_ISSUE_NUMBER }}
        comment-author: 'github-actions[bot]'

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ vars.LOCALIZATION_TRACKER_ISSUE_NUMBER }}
        body: |
          [github actions placeholder text]

    - name: Main table timestamp
      id: main-timestamp
      if: steps.fc.outputs.comment-id != ''
      env:
        TRACKER_FILE_PATH: ${{ vars.LOCALIZATION_TRACKING_TABLES }}/tracker.csv
      run: |
        echo $(git log -1 --date=iso-local --format="%ad" -- $TRACKER_FILE_PATH)
        echo $(git log -1 --date=iso-local -- $TRACKER_FILE_PATH)
        echo "TIMESTAMP=$(git log -1 --date=iso-local --format="%ad" -- $TRACKER_FILE_PATH)" >> ${GITHUB_OUTPUT}

    - name: Render template
      id: template
      if: steps.fc.outputs.comment-id != ''
      uses: chuhlomin/render-template@v1.6
      with:
        template: ${{ vars.LOCALIZATION_TRACKING_MARKDOWN }}/header.md
        vars: |
          timestamp: ${{ steps.timestamp.outputs.TIMESTAMP }}

    - name: Insert header
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
        body: ${{ steps.template.outputs.result }}

    - name: Read main CSV
      id: main-csv
      if: steps.fc.outputs.comment-id != ''
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ vars.LOCALIZATION_TRACKING_TABLES }}/tracker.csv

    - name: Main table markdown
      id: main-md
      if: steps.fc.outputs.comment-id != ''
      uses: petems/csv-to-md-table-action@master
      with:
        csvinput: ${{ steps.main-csv.outputs.content }}

    - name: Insert main table
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: append
        body: ${{ steps.main-md.outputs.markdown-table }}

    - name: Clues table timestamp
      id: clues-timestamp
      if: steps.fc.outputs.comment-id != ''
      env:
        TRACKER_FILE_PATH: ${{ vars.LOCALIZATION_TRACKING_TABLES }}/tracker.csv
      run: |
        echo $(git log -1 --date=iso-local --format="%ad" -- $TRACKER_FILE_PATH)
        echo $(git log -1 --date=iso-local -- $TRACKER_FILE_PATH)
        echo "TIMESTAMP=$(git log -1 --date=iso-local --format="%ad" -- $TRACKER_FILE_PATH)" >> ${GITHUB_OUTPUT}

    - name: Clues template
      id: clues-template
      if: steps.fc.outputs.comment-id != ''
      uses: chuhlomin/render-template@v1.6
      with:
        template: ${{ vars.LOCALIZATION_TRACKING_MARKDOWN }}/clues.md
        vars: |
          timestamp: ${{ steps.clues-timestamp.outputs.TIMESTAMP }}

    - name: Clues header
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: append
        body: ${{ steps.clues-template.outputs.result }}

    - name: Read clues CSV
      id: clues-csv
      if: steps.fc.outputs.comment-id != ''
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ vars.LOCALIZATION_TRACKING_TABLES }}/clues.csv

    - name: Clues table markdown
      id: clues-md
      if: steps.fc.outputs.comment-id != ''
      uses: petems/csv-to-md-table-action@master
      with:
        csvinput: ${{ steps.clues-csv.outputs.content }}

    - name: Insert clues table
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: append
        body: ${{ steps.clues-md.outputs.markdown-table }}
